title:               Mentoring SuperHighway
url:                 https://mentoring-superhighway.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           dark
paginate:            2
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed


plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
